name: Copy folder to other branch

on: [workflow_dispatch]

jobs:
  copy:
    name: Copy my folder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy To Branches Action
        uses: planetoftheweb/copy-to-branches@v1.2
        env:
          branches: gh-pages
          key: main
          files: src/*
